import Head from 'next/head';
import styles from '../styles/About.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>You Can Movement - Quem somos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>Sobre</h3>
      <p>
        There are many variations of passages of Lorem Ipsum available, but the
        majority have suffered.There are many variations of passages of Lorem
        Ipsum available, but the majority have suffered. There are many
        variations of passages of Lorem Ipsum available, but the majority have
        suffered. There are many variations of passages of Lorem Ipsum
        available, but the majority have suffered. There are many variations of
        passages of Lorem Ipsum available, but the majority have suffered.
      </p>
    </div>
  );
}
