import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Community() {
  return (
    <div className={styles.container}>
      <Head>
        <title>You Can Movement - Comunidade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>Se conecte com novas pessoase</h3>
      <p>
        Como funciona? Escolha alguém que mais te chamou atenção e entre em
        contato com essa pessoa e comece seu network, esse é o primeiro passo
        para conquistar seu objetivo. Juntos vamos longe.
      </p>
    </div>
  );
}
