import Head from 'next/head';
import { google } from 'googleapis';

import styles from '../../styles/Community.module.css';

interface Community {
  membros: string[];
  comunidades: string[];
  selected: string;
}

export async function getServerSideProps({ query }) {
  const auth = await google.auth.getClient({
    scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
  });

  const sheets = google.sheets({ version: 'v4', auth });

  const response = await sheets.spreadsheets.values.get({
    spreadsheetId: process.env.SHEET_ID,
    range: 'membros',
  });

  let membros = response.data.values;
  membros = membros?.slice(1);
  console.log(`-----membros----- \n${membros}`);

  const comunidades = [...new Set(membros.map(item => item[2]))].sort();

  console.log(`-----comunidades----- \n${comunidades}`);
  const { selected } = query;

  console.log(`-----selected-----`);
  console.log(selected);

  return {
    props: {
      membros,
      comunidades,
      selected,
    },
  };
}

export default function Community({
  selected,
  comunidades,
  membros,
}: Community) {
  return (
    <div className={styles.container}>
      <Head>
        <title>You Can Movement - Comunidade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>Se conecte com novas pessoase</h3>
      <p>
        Como funciona? Escolha alguém que mais te chamou atenção e entre em
        contato com essa pessoa e comece seu network, esse é o primeiro passo
        para conquistar seu objetivo. Juntos vamos longe.
      </p>

      <div className={styles.communities}>
        <h4 id={styles.selected}>Educação</h4>
        <h4>Design e Comunicação</h4>
        <h4>Empreendedorismo</h4>
        <h4>Tecnologia</h4>
        <h4>Direito</h4>
        <h4>Política</h4>
        <h4>Bolsa de estudos</h4>
        <h4>Carreira</h4>
        <h4>Inclusão Social</h4>
        <h4>Impacto Social</h4>
        <h4>Autoconhecimento</h4>
        <h4>Liderança</h4>
      </div>
    </div>
  );
}
