import Head from 'next/head';
import Link from 'next/link';

import MemberCard from '../../components/MemberCard';
import GetSheetFromGoogle from '../../utils/GetSheetFromGoogle';

import styles from '../../styles/Community.module.css';

interface Community {
  membros: string[];
  comunidades: string[];
}

export async function getStaticProps() {
  const membros = await GetSheetFromGoogle('membros');

  const comunidades = [...new Set(membros?.map(item => item[3]))].sort();

  return {
    props: {
      membros,
      comunidades,
    },
    revalidate: 5, // In seconds
  };
}

export default function Community({ comunidades, membros }: Community) {
  return (
    <div className={styles.container}>
      <Head>
        <title>You Can Movement - Comunidade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>Se conecte com novas pessoas</h3>
      <p>
        Como funciona? Escolha alguém que mais te chamou atenção e entre em
        contato com essa pessoa e comece seu network, esse é o primeiro passo
        para conquistar seu objetivo. Juntos vamos longe.
      </p>

      <div className={styles.communities}>
        {comunidades.map((comunidade, index) => (
          <div className={styles.notSelected} key={index}>
            <Link href={`/community/${comunidade}`}>{comunidade}</Link>
          </div>
        ))}
      </div>

      <div className={styles.members}>
        {membros.map((membro, index) => (
          <MemberCard
            key={index}
            nome={membro[0]}
            idade={membro[1]}
            foto={membro[2]}
            resumo={membro[4]}
            instagram={membro[5]}
            linkedin={membro[6]}
            facebook={membro[7]}
          />
        ))}
      </div>
    </div>
  );
}
