import Head from 'next/head';
import { google } from 'googleapis';

import MemberCard from '../../components/MemberCard';

import styles from '../../styles/Community.module.css';

interface Community {
  membros: string[];
  comunidades: string[];
}

export async function getServerSideProps({ query }) {
  const auth = await google.auth.getClient({
    scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
  });

  const sheets = google.sheets({ version: 'v4', auth });

  const response = await sheets.spreadsheets.values.get({
    spreadsheetId: process.env.SHEET_ID,
    range: 'membros',
  });

  let membros = response.data.values;
  membros = membros?.slice(1);
  console.log(`-----membros----- \n${membros}`);

  const comunidades = [...new Set(membros.map(item => item[3]))].sort();

  console.log(`-----comunidades----- \n${comunidades}`);
  console.log(`-----query----- \n${query}`);

  return {
    props: {
      membros,
      comunidades,
    },
  };
}

export default function Community({ comunidades, membros }: Community) {
  return (
    <div className={styles.container}>
      <Head>
        <title>You Can Movement - Comunidade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>Se conecte com novas pessoase</h3>
      <p>
        Como funciona? Escolha alguém que mais te chamou atenção e entre em
        contato com essa pessoa e comece seu network, esse é o primeiro passo
        para conquistar seu objetivo. Juntos vamos longe.
      </p>

      <div className={styles.communities}>
        {comunidades.map((comunidade, index) => (
          <h4 key={index}>{comunidade}</h4>
        ))}
      </div>

      <div className={styles.members}>
        {membros.map((membro, index) => (
          <MemberCard
            key={index}
            nome={membro[0]}
            idade={membro[1]}
            foto={membro[2]}
            resumo={membro[4]}
            instagram={membro[5]}
            linkedin={membro[6]}
            facebook={membro[7]}
          />
        ))}
      </div>
    </div>
  );
}
